non_trivial:
  - '**'
  - '!**/*.adoc'
  - '!**/*.md'
  - '!**/*.mdx'
  - '!**/*.pdf'
  - '!**/*.png'
  - '!**/*.jpg'
  - '!**/*.jpeg'
  - '!**/*.gif'
  - '!**/*.bmp'
  - '!**/*.ico'
  - '!**/*.webp'
  - '!**/*.rst'
  - '!**/*.svg'
  - '!**/*.txt'
  - '!LICENSE'
